# Generated by Django 5.1.4 on 2024-12-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero_cta_homepage_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
